// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/drp/message.proto

package drp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Login
	//	*Envelope_NewProxy
	//	*Envelope_NewWorkConn
	//	*Envelope_Ping
	//	*Envelope_LoginResp
	//	*Envelope_NewProxyResp
	//	*Envelope_ReqWorkConn
	//	*Envelope_StartWorkConn
	//	*Envelope_Pong
	//	*Envelope_RelayOpen
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_drp_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drp_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_drp_message_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetLogin() *Login {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Login); ok {
			return x.Login
		}
	}
	return nil
}

func (x *Envelope) GetNewProxy() *NewProxy {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_NewProxy); ok {
			return x.NewProxy
		}
	}
	return nil
}

func (x *Envelope) GetNewWorkConn() *NewWorkConn {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_NewWorkConn); ok {
			return x.NewWorkConn
		}
	}
	return nil
}

func (x *Envelope) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Envelope) GetLoginResp() *LoginResp {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_LoginResp); ok {
			return x.LoginResp
		}
	}
	return nil
}

func (x *Envelope) GetNewProxyResp() *NewProxyResp {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_NewProxyResp); ok {
			return x.NewProxyResp
		}
	}
	return nil
}

func (x *Envelope) GetReqWorkConn() *ReqWorkConn {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ReqWorkConn); ok {
			return x.ReqWorkConn
		}
	}
	return nil
}

func (x *Envelope) GetStartWorkConn() *StartWorkConn {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_StartWorkConn); ok {
			return x.StartWorkConn
		}
	}
	return nil
}

func (x *Envelope) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *Envelope) GetRelayOpen() *RelayOpen {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RelayOpen); ok {
			return x.RelayOpen
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Login struct {
	// 클라이언트 → 서버
	Login *Login `protobuf:"bytes,1,opt,name=login,proto3,oneof"`
}

type Envelope_NewProxy struct {
	NewProxy *NewProxy `protobuf:"bytes,2,opt,name=new_proxy,json=newProxy,proto3,oneof"`
}

type Envelope_NewWorkConn struct {
	NewWorkConn *NewWorkConn `protobuf:"bytes,3,opt,name=new_work_conn,json=newWorkConn,proto3,oneof"`
}

type Envelope_Ping struct {
	Ping *Ping `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

type Envelope_LoginResp struct {
	// 서버 → 클라이언트
	LoginResp *LoginResp `protobuf:"bytes,10,opt,name=login_resp,json=loginResp,proto3,oneof"`
}

type Envelope_NewProxyResp struct {
	NewProxyResp *NewProxyResp `protobuf:"bytes,11,opt,name=new_proxy_resp,json=newProxyResp,proto3,oneof"`
}

type Envelope_ReqWorkConn struct {
	ReqWorkConn *ReqWorkConn `protobuf:"bytes,12,opt,name=req_work_conn,json=reqWorkConn,proto3,oneof"`
}

type Envelope_StartWorkConn struct {
	StartWorkConn *StartWorkConn `protobuf:"bytes,13,opt,name=start_work_conn,json=startWorkConn,proto3,oneof"`
}

type Envelope_Pong struct {
	Pong *Pong `protobuf:"bytes,14,opt,name=pong,proto3,oneof"`
}

type Envelope_RelayOpen struct {
	// 서버 ↔ 서버 (QUIC relay)
	RelayOpen *RelayOpen `protobuf:"bytes,20,opt,name=relay_open,json=relayOpen,proto3,oneof"`
}

func (*Envelope_Login) isEnvelope_Payload() {}

func (*Envelope_NewProxy) isEnvelope_Payload() {}

func (*Envelope_NewWorkConn) isEnvelope_Payload() {}

func (*Envelope_Ping) isEnvelope_Payload() {}

func (*Envelope_LoginResp) isEnvelope_Payload() {}

func (*Envelope_NewProxyResp) isEnvelope_Payload() {}

func (*Envelope_ReqWorkConn) isEnvelope_Payload() {}

func (*Envelope_StartWorkConn) isEnvelope_Payload() {}

func (*Envelope_Pong) isEnvelope_Payload() {}

func (*Envelope_RelayOpen) isEnvelope_Payload() {}

type Login struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Login) Reset() {
	*x = Login{}
	mi := &file_proto_drp_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login) ProtoMessage() {}

func (x *Login) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drp_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login.ProtoReflect.Descriptor instead.
func (*Login) Descriptor() ([]byte, []int) {
	return file_proto_drp_message_proto_rawDescGZIP(), []int{1}
}

func (x *Login) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Login) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type NewProxy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // "http" | "https"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewProxy) Reset() {
	*x = NewProxy{}
	mi := &file_proto_drp_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewProxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewProxy) ProtoMessage() {}

func (x *NewProxy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drp_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewProxy.ProtoReflect.Descriptor instead.
func (*NewProxy) Descriptor() ([]byte, []int) {
	return file_proto_drp_message_proto_rawDescGZIP(), []int{2}
}

func (x *NewProxy) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *NewProxy) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NewProxy) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type NewWorkConn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProxyAlias    string                 `protobuf:"bytes,1,opt,name=proxy_alias,json=proxyAlias,proto3" json:"proxy_alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewWorkConn) Reset() {
	*x = NewWorkConn{}
	mi := &file_proto_drp_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewWorkConn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewWorkConn) ProtoMessage() {}

func (x *NewWorkConn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drp_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewWorkConn.ProtoReflect.Descriptor instead.
func (*NewWorkConn) Descriptor() ([]byte, []int) {
	return file_proto_drp_message_proto_rawDescGZIP(), []int{3}
}

func (x *NewWorkConn) GetProxyAlias() string {
	if x != nil {
		return x.ProxyAlias
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_proto_drp_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drp_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_drp_message_proto_rawDescGZIP(), []int{4}
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_proto_drp_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drp_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_proto_drp_message_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LoginResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NewProxyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewProxyResp) Reset() {
	*x = NewProxyResp{}
	mi := &file_proto_drp_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewProxyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewProxyResp) ProtoMessage() {}

func (x *NewProxyResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drp_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewProxyResp.ProtoReflect.Descriptor instead.
func (*NewProxyResp) Descriptor() ([]byte, []int) {
	return file_proto_drp_message_proto_rawDescGZIP(), []int{6}
}

func (x *NewProxyResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *NewProxyResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReqWorkConn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProxyAlias    string                 `protobuf:"bytes,1,opt,name=proxy_alias,json=proxyAlias,proto3" json:"proxy_alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqWorkConn) Reset() {
	*x = ReqWorkConn{}
	mi := &file_proto_drp_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqWorkConn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqWorkConn) ProtoMessage() {}

func (x *ReqWorkConn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drp_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqWorkConn.ProtoReflect.Descriptor instead.
func (*ReqWorkConn) Descriptor() ([]byte, []int) {
	return file_proto_drp_message_proto_rawDescGZIP(), []int{7}
}

func (x *ReqWorkConn) GetProxyAlias() string {
	if x != nil {
		return x.ProxyAlias
	}
	return ""
}

type StartWorkConn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProxyAlias    string                 `protobuf:"bytes,1,opt,name=proxy_alias,json=proxyAlias,proto3" json:"proxy_alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkConn) Reset() {
	*x = StartWorkConn{}
	mi := &file_proto_drp_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkConn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkConn) ProtoMessage() {}

func (x *StartWorkConn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drp_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkConn.ProtoReflect.Descriptor instead.
func (*StartWorkConn) Descriptor() ([]byte, []int) {
	return file_proto_drp_message_proto_rawDescGZIP(), []int{8}
}

func (x *StartWorkConn) GetProxyAlias() string {
	if x != nil {
		return x.ProxyAlias
	}
	return ""
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_proto_drp_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drp_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_proto_drp_message_proto_rawDescGZIP(), []int{9}
}

type RelayOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProxyAlias    string                 `protobuf:"bytes,1,opt,name=proxy_alias,json=proxyAlias,proto3" json:"proxy_alias,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayOpen) Reset() {
	*x = RelayOpen{}
	mi := &file_proto_drp_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayOpen) ProtoMessage() {}

func (x *RelayOpen) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drp_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayOpen.ProtoReflect.Descriptor instead.
func (*RelayOpen) Descriptor() ([]byte, []int) {
	return file_proto_drp_message_proto_rawDescGZIP(), []int{10}
}

func (x *RelayOpen) GetProxyAlias() string {
	if x != nil {
		return x.ProxyAlias
	}
	return ""
}

func (x *RelayOpen) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ServiceUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // "add" | "remove"
	ProxyAlias    string                 `protobuf:"bytes,3,opt,name=proxy_alias,json=proxyAlias,proto3" json:"proxy_alias,omitempty"`
	Hostname      string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceUpdate) Reset() {
	*x = ServiceUpdate{}
	mi := &file_proto_drp_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceUpdate) ProtoMessage() {}

func (x *ServiceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drp_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceUpdate.ProtoReflect.Descriptor instead.
func (*ServiceUpdate) Descriptor() ([]byte, []int) {
	return file_proto_drp_message_proto_rawDescGZIP(), []int{11}
}

func (x *ServiceUpdate) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ServiceUpdate) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ServiceUpdate) GetProxyAlias() string {
	if x != nil {
		return x.ProxyAlias
	}
	return ""
}

func (x *ServiceUpdate) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type NodeServices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostnames     []string               `protobuf:"bytes,1,rep,name=hostnames,proto3" json:"hostnames,omitempty"`
	QuicAddr      string                 `protobuf:"bytes,2,opt,name=quic_addr,json=quicAddr,proto3" json:"quic_addr,omitempty"` // e.g. "10.0.0.1:9001"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeServices) Reset() {
	*x = NodeServices{}
	mi := &file_proto_drp_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeServices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeServices) ProtoMessage() {}

func (x *NodeServices) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drp_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeServices.ProtoReflect.Descriptor instead.
func (*NodeServices) Descriptor() ([]byte, []int) {
	return file_proto_drp_message_proto_rawDescGZIP(), []int{12}
}

func (x *NodeServices) GetHostnames() []string {
	if x != nil {
		return x.Hostnames
	}
	return nil
}

func (x *NodeServices) GetQuicAddr() string {
	if x != nil {
		return x.QuicAddr
	}
	return ""
}

var File_proto_drp_message_proto protoreflect.FileDescriptor

const file_proto_drp_message_proto_rawDesc = "" +
	"\n" +
	"\x17proto/drp/message.proto\x12\x06drp.v1\"\x92\x04\n" +
	"\bEnvelope\x12%\n" +
	"\x05login\x18\x01 \x01(\v2\r.drp.v1.LoginH\x00R\x05login\x12/\n" +
	"\tnew_proxy\x18\x02 \x01(\v2\x10.drp.v1.NewProxyH\x00R\bnewProxy\x129\n" +
	"\rnew_work_conn\x18\x03 \x01(\v2\x13.drp.v1.NewWorkConnH\x00R\vnewWorkConn\x12\"\n" +
	"\x04ping\x18\x04 \x01(\v2\f.drp.v1.PingH\x00R\x04ping\x122\n" +
	"\n" +
	"login_resp\x18\n" +
	" \x01(\v2\x11.drp.v1.LoginRespH\x00R\tloginResp\x12<\n" +
	"\x0enew_proxy_resp\x18\v \x01(\v2\x14.drp.v1.NewProxyRespH\x00R\fnewProxyResp\x129\n" +
	"\rreq_work_conn\x18\f \x01(\v2\x13.drp.v1.ReqWorkConnH\x00R\vreqWorkConn\x12?\n" +
	"\x0fstart_work_conn\x18\r \x01(\v2\x15.drp.v1.StartWorkConnH\x00R\rstartWorkConn\x12\"\n" +
	"\x04pong\x18\x0e \x01(\v2\f.drp.v1.PongH\x00R\x04pong\x122\n" +
	"\n" +
	"relay_open\x18\x14 \x01(\v2\x11.drp.v1.RelayOpenH\x00R\trelayOpenB\t\n" +
	"\apayload\":\n" +
	"\x05Login\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"P\n" +
	"\bNewProxy\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\".\n" +
	"\vNewWorkConn\x12\x1f\n" +
	"\vproxy_alias\x18\x01 \x01(\tR\n" +
	"proxyAlias\"\x06\n" +
	"\x04Ping\"1\n" +
	"\tLoginResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"4\n" +
	"\fNewProxyResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\".\n" +
	"\vReqWorkConn\x12\x1f\n" +
	"\vproxy_alias\x18\x01 \x01(\tR\n" +
	"proxyAlias\"0\n" +
	"\rStartWorkConn\x12\x1f\n" +
	"\vproxy_alias\x18\x01 \x01(\tR\n" +
	"proxyAlias\"\x06\n" +
	"\x04Pong\"K\n" +
	"\tRelayOpen\x12\x1f\n" +
	"\vproxy_alias\x18\x01 \x01(\tR\n" +
	"proxyAlias\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"}\n" +
	"\rServiceUpdate\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1f\n" +
	"\vproxy_alias\x18\x03 \x01(\tR\n" +
	"proxyAlias\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\"I\n" +
	"\fNodeServices\x12\x1c\n" +
	"\thostnames\x18\x01 \x03(\tR\thostnames\x12\x1b\n" +
	"\tquic_addr\x18\x02 \x01(\tR\bquicAddrB%Z#github.com/cagojeiger/drp/proto/drpb\x06proto3"

var (
	file_proto_drp_message_proto_rawDescOnce sync.Once
	file_proto_drp_message_proto_rawDescData []byte
)

func file_proto_drp_message_proto_rawDescGZIP() []byte {
	file_proto_drp_message_proto_rawDescOnce.Do(func() {
		file_proto_drp_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_drp_message_proto_rawDesc), len(file_proto_drp_message_proto_rawDesc)))
	})
	return file_proto_drp_message_proto_rawDescData
}

var file_proto_drp_message_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_drp_message_proto_goTypes = []any{
	(*Envelope)(nil),      // 0: drp.v1.Envelope
	(*Login)(nil),         // 1: drp.v1.Login
	(*NewProxy)(nil),      // 2: drp.v1.NewProxy
	(*NewWorkConn)(nil),   // 3: drp.v1.NewWorkConn
	(*Ping)(nil),          // 4: drp.v1.Ping
	(*LoginResp)(nil),     // 5: drp.v1.LoginResp
	(*NewProxyResp)(nil),  // 6: drp.v1.NewProxyResp
	(*ReqWorkConn)(nil),   // 7: drp.v1.ReqWorkConn
	(*StartWorkConn)(nil), // 8: drp.v1.StartWorkConn
	(*Pong)(nil),          // 9: drp.v1.Pong
	(*RelayOpen)(nil),     // 10: drp.v1.RelayOpen
	(*ServiceUpdate)(nil), // 11: drp.v1.ServiceUpdate
	(*NodeServices)(nil),  // 12: drp.v1.NodeServices
}
var file_proto_drp_message_proto_depIdxs = []int32{
	1,  // 0: drp.v1.Envelope.login:type_name -> drp.v1.Login
	2,  // 1: drp.v1.Envelope.new_proxy:type_name -> drp.v1.NewProxy
	3,  // 2: drp.v1.Envelope.new_work_conn:type_name -> drp.v1.NewWorkConn
	4,  // 3: drp.v1.Envelope.ping:type_name -> drp.v1.Ping
	5,  // 4: drp.v1.Envelope.login_resp:type_name -> drp.v1.LoginResp
	6,  // 5: drp.v1.Envelope.new_proxy_resp:type_name -> drp.v1.NewProxyResp
	7,  // 6: drp.v1.Envelope.req_work_conn:type_name -> drp.v1.ReqWorkConn
	8,  // 7: drp.v1.Envelope.start_work_conn:type_name -> drp.v1.StartWorkConn
	9,  // 8: drp.v1.Envelope.pong:type_name -> drp.v1.Pong
	10, // 9: drp.v1.Envelope.relay_open:type_name -> drp.v1.RelayOpen
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_drp_message_proto_init() }
func file_proto_drp_message_proto_init() {
	if File_proto_drp_message_proto != nil {
		return
	}
	file_proto_drp_message_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Login)(nil),
		(*Envelope_NewProxy)(nil),
		(*Envelope_NewWorkConn)(nil),
		(*Envelope_Ping)(nil),
		(*Envelope_LoginResp)(nil),
		(*Envelope_NewProxyResp)(nil),
		(*Envelope_ReqWorkConn)(nil),
		(*Envelope_StartWorkConn)(nil),
		(*Envelope_Pong)(nil),
		(*Envelope_RelayOpen)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_drp_message_proto_rawDesc), len(file_proto_drp_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_drp_message_proto_goTypes,
		DependencyIndexes: file_proto_drp_message_proto_depIdxs,
		MessageInfos:      file_proto_drp_message_proto_msgTypes,
	}.Build()
	File_proto_drp_message_proto = out.File
	file_proto_drp_message_proto_goTypes = nil
	file_proto_drp_message_proto_depIdxs = nil
}
