FROM alpine:3.20

ARG FRP_VERSION=0.68.0
ARG TARGETARCH

RUN apk add --no-cache curl && \
    ARCH=$(case "${TARGETARCH}" in amd64) echo "amd64";; arm64) echo "arm64";; *) echo "amd64";; esac) && \
    curl -fSL "https://github.com/fatedier/frp/releases/download/v${FRP_VERSION}/frp_${FRP_VERSION}_linux_${ARCH}.tar.gz" \
      | tar xz --strip-components=1 -C /usr/local/bin/ \
        "frp_${FRP_VERSION}_linux_${ARCH}/frpc" \
        "frp_${FRP_VERSION}_linux_${ARCH}/frps"
